#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
substitute="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$substitute/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx restart
