#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "# Own server configuration
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /var/www/html;
                internal;
        }
        add_header X-Served-By "$HOSTNAME";
        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx restart