#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt-get -y install haproxy
echo "
frontend http
        bind *:80
        mode http
        default_backend ale_backend

backend ale_backend
        balance roundrobin
        server 2254-web-01 35.231.58.206:80
        server 2254-web-02 34.74.180.55:80
" >> /etc/haproxy/haproxy.cfg
service haproxy restart