#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt-get -y install haproxy
echo "
frontend http
        bind *:80
        mode http
        default_backend ale_backend

backend ale_backend
        balance roundrobin
        server web1 35.231.58.206:80 check
        server web2 34.74.180.55:80 check
" > /etc/haproxy/haproxy.cfg
service haproxy restart