#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
cp sites-available/default sites-enabled/default
service nginx reload
kill -HUP $(ps -ef | grep nginx | grep master | awk '{print $2}')
