#!/usr/bin/env bash
# Create a file, display
# handle signals
FILE=/var/run/holbertonscript.pid
echo $$ >> $FILE
trap 'echo "I hate the kill command"; rm $FILE; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm $FILE; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
