#!/usr/bin/env bash
#script that displays numbers from 1 to 20 and others conditions using case stament

LIMIT=21
i=1
while (( i < LIMIT ))
do
    echo "$i"
    case $i in
	4 )
	    echo "bad luck from China";;
	9 )
	    echo "bad luck from Japan";;
	17 )
	    echo "bad luck from Italy";;
    esac

    let "i+=1"
done
