#!/usr/bin/env bash
#  script that displays the time for 12 hours and 59 minutes


H=13
L=60
i=0
j=1
while (( i < H ))
do
    echo "Hour: $i"
    j=1
    while(( j < L ))
    do
	echo "$j"
	(( j++ ))
    done
    (( i++ ))
done
