#!/usr/bin/env bash
# nginx running as nginx user, alsa must be listening on pot 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
