#!/usr/bin/env bash
# nginx running as nginx user, alsa must be listening on pot 8080
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i "/nginx.pid;/ a \user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
